---
- name: "Copy files to server"
  become: true
  copy:
    src: "artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"
- name: "Unzip files as backend folder"
  command: tar -xzf artifact.tar.gz
  become: true
  args:
    chdir: /home/ubuntu/
- name: "Install dependencies"
  command: npm install
  become: true
  args:
    chdir: /home/ubuntu/backend
- name: "Run the app with PM2"
  command: pm2 start npm -- start
  args:
    chdir: /home/ubuntu/backend
